spring.datasource.url=jdbc:postgresql://localhost:5432/db_dispo_horario_uts
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# create, create-drop, validate, update
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=debug

#spring.profiles.active=${PROFILE:dev} -- Descomentar para usar el perfil de desarrollo


user.default.gmail=${USER_DEFAULT:correo}
pass.default.gmail=${PASS_DEFAULT:contra}
twilio.account.sid=${TWILIO_ACCOUNT_SID:asdfsaddfasdfsa}
twilio.auth.token=${TWILIO_AUTH_TOKEN:asdfasdfasfsda}
twilio.phone.number=${TWILIO_PHONE_NUMBER:+11234567899}